[package]
name = "egui_wgpu_backend"
version = "0.2.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
edition = "2018"
description = "Backend code to use egui with wgpu."
homepage = "https://github.com/hasenbanck/egui_wgpu_backend"
repository = "https://github.com/hasenbanck/egui_wgpu_backend"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
egui = "0.3"
wgpu = "0.6"
bytemuck = "1.4"
vk-shader-macros = "0.2"
